<?php
$sugar_config_si = array (
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollars',
    'default_currency_significant_digits' => '2',
    'default_currency_symbol' => '$',
    'default_date_format' => 'Y-m-d',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator'    => ',',
    'default_time_format' => 'H:i',
    'export_delimiter' => ',',
    'setup_db_admin_password' => '{{ mysql_root_password }}', // DATABASE ADMIN USER PASSWORD
    'setup_db_admin_user_name' => '{{ mysql_root_username }}', // DATABASE ADMIN USER NAME
    'setup_db_create_database' => '1', // CREATE THE DATABASE IF IT DOESN'T EXIST
    'setup_db_drop_tables' => '1', // DROP THE TABLES IF THEY EXIST
    'setup_db_sugarsales_password' => '{{ mysql_root_password }}', // THE DATABASE PASSWORD TO USE AFTER INSTALLATION TO CONNECT
    'setup_db_sugarsales_password_retype' => '{{ mysql_root_password }}', // AGAIN
    'setup_db_sugarsales_user' => '{{ mysql_root_username }}', // THE DATABASE USER TO USE AFTER INSTALLATION TO CONNECT
    'setup_db_type' => 'mysql', // OR OTHER DATABASE TYPE (ibm_db2, etc)
    'setup_db_host_name' => 'localhost', // DATABASE HOST LOCATION
    'setup_db_port_num' => '3306', // DATABASE PORT
    'setup_db_create_sugarsales_user' => 0, // CREATE THE DATABASE USER TO USE AFTER INSTALLATION
    'setup_db_database_name' => '{{ sugar_db_name }}', // THE DATABASE NAME
    'setup_db_pop_demo_data' => 0, // (0 or 1) POPULATE DEMO DATA
    'dbUSRData' => 'same',
    'demoData' => 'no', // (yes or no) POPULATE DEMO DATA
    'setup_license_key' => '{{ sugar_license_key }}', // License Key
    'setup_site_admin_user_name'=> '{{ sugar_admin_user }}', // SUGAR ADMIN USER NAME
    'setup_site_admin_password' => '{{ sugar_admin_password }}', // SUGAR ADMIN PASSWORD
    'setup_site_url' => '{{ site_url }}', // PATH TO SUGAR INSTANCE VIA URL
    'setup_system_name' => '*** My SugarCRM Instance *** '.date('Y-m-d H:i'), // INSTANCE NAME
    'setup_fts_type' => 'Elastic', // TYPE OF FULL TEXT SEARCH
    'setup_fts_host' => 'localhost', // HOST FOR FULL TEXT SEARCH
    'setup_fts_port' => '9200', // PORT NUMBER FOR FULL TEXT SEARCH
);
